name: Deploy

on:
  push:
    branches: [ master  ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}
      
        run: |
          echo "$PRIVATE_KEY" > private_key.pem && chmod 600 private_key.pem
          cat ./private_key.pem
          echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
          ssh -i ./private_key.pem ubuntu@52.34.98.171
              # Now we have got the access of EC2 and we will start the deploy .
              touch /home/ubuntu/helloworld &&
              cd /home/ubuntu/express-hello-world &&
              git checkout master &&
              git fetch --all &&
              git reset --hard origin/master &&
              git pull origin master &&
              sudo npm i &&
              sudo pm2 stop ./index.js &&
              sudo pm2 start ./index.js
