name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  run_example_job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: print out example job
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY  }}
        port: 22
        command_timeout: 30m
        script: | 
          echo "Nice Job!!!"
          cd /home/ubuntu/express-hello-world &&
          git checkout master &&
          git fetch --all &&
          git reset --hard origin/master &&
          git pull origin master &&
          sudo npm i &&
          sudo pm2 stop ./index.js &&
          sudo pm2 start ./index.js
