name: Deploy

on:
  push:
    branches: [ master  ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      
      - name: Run a script
        run: |
          echo "Starting the build process..."
          # 假设你有一个构建命令
          echo "Building the application..."
          # 这里可以是你的构建命令
          echo "Build completed successfully."
          
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}
            
        run: |
          echo "12132312312"
          echo "243234234234234234"
          echo "qwerqwer${{env.HOSTNAME}}"
          echo "weew----${{env.USER_NAME}}"
          echo "${{env.PRIVATE_KEY}}" > private_key && chmod 600 private_key
          ssh -i private_key ${env.USER_NAME}@${env.HOSTNAME}
              # Now we have got the access of EC2 and we will start the deploy .
              touch /home/ubuntu/helloworld &&
              cd /home/ubuntu/express-hello-world &&
              git checkout master &&
              git fetch --all &&
              git reset --hard origin/master &&
              git pull origin master &&
              sudo npm i &&
              sudo pm2 stop ./index.js &&
              sudo pm2 start ./index.js
